version: 2
registries:
  npm-registry:
    type: npm-registry
    url: https://npm.pkg.github.com/watersport
    token: ${{secrets.DEPENDABOT_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-registry
    schedule:
      interval: "daily"
    target-branch: "feature/WAT-1069-Initialize-components-react-library"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "@watersport*"
    assignees:
      - dependabot[bot]
    reviewers:
      - Sergey-Xursevich
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    versioning-strategy: "auto"